[package]
name = "test3"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24.0"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
env_logger = "0.11.6"
futures = "0.3" 


[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
